
name: Internet Protocol Version 7
year: 2016
day: 07

tests:
  - part: 1
    run: true
    debugRun: true
    expected: 2
    knownErrors:
    source: test.txt
    
  - part: 2
    run: true
    debugRun: true
    expected: 3
    knownErrors:
    source: test2.txt
    
live:
  - part: 1
    run: true
    debugRun: true
    expected: 118
    knownErrors:
    source: live.txt

  - part: 2
    run: true
    debugRun: true
    expected: 260
    knownErrors:
    source: live.txt
