
name: Signals and Noise
year: 2016
day: 06

tests:
  - part: 1
    run: true
    debugRun: true
    expected: easter
    knownErrors:
    source: test.txt
    
  - part: 2
    run: true
    debugRun: true
    expected: advent
    knownErrors:
    source: test.txt
    
live:
  - part: 1
    run: true
    debugRun: true
    expected: afwlyyyq
    knownErrors:
    source: live.txt

  - part: 2
    run: true
    debugRun: true
    expected: bhkzekao
    knownErrors:
    source: live.txt
