
name: Bathroom Security
year: 2016
day: 02

tests:
  - part: 1
    run: true
    debugRun: true
    expected: '1985'
    knownErrors:
    source: |
     ULL
     RRDDD
     LURDL
     UUUUD    
    
  - part: 2
    run: true
    debugRun: true
    expected: 5DB3
    knownErrors:
    source: |
     ULL
     RRDDD
     LURDL
     UUUUD    
    
live:
  - part: 1
    run: true
    debugRun: true
    expected: '12578'
    knownErrors:
    source: live.txt

  - part: 2
    run: true
    debugRun: true
    expected: 516DD
    knownErrors:
    source: live.txt
