
name: Cafeteria
year: 2025
day: 5
benchmark: true

tests:
  - part: 1
    run: true
    debugRun: true
    expected: 3
    knownErrors:
    showVisualisation: false
    source: test.txt
    
  - part: 2
    run: true
    debugRun: true
    expected: 14
    knownErrors:
    showVisualisation: false
    source: test.txt
    
live:
  - part: 1
    run: true
    debugRun: true
    expected: 773
    knownErrors:
    showVisualisation: false
    source: live.txt

  - part: 2
    run: true
    debugRun: true
    expected: 332067203034711
    knownErrors:
    showVisualisation: false
    source: live.txt
