
name: Squares With Three Sides
year: 2016
day: 03

tests:
  - part: 1
    run: true
    debugRun: true
    expected: '0'
    knownErrors:
    source: '  5 10 25'
    
  - part: 2
    run: true
    debugRun: true
    expected: '6'
    knownErrors:
    source: test2.txt
    
live:
  - part: 1
    run: true
    debugRun: true
    expected: '869'
    knownErrors:
    source: live.txt

  - part: 2
    run: true
    debugRun: true
    expected: '1544'
    knownErrors:
    source: live.txt
