
name: Security Through Obscurity
year: 2016
day: 04

tests:
  - part: 1
    run: true
    debugRun: true
    expected: 1514
    knownErrors:
    source: test1.txt
    
  - part: 2
    run: true
    debugRun: true
    expected: 0
    knownErrors:
    source: test2.txt
    
live:
  - part: 1
    run: true
    debugRun: true
    expected: 158835
    knownErrors:
    source: live.txt

  - part: 2
    run: true
    debugRun: true
    expected: 993
    knownErrors:
    source: live.txt
