
name: How About a Nice Game of Chess?
year: 2016
day: 05

tests:
  - part: 1
    run: true
    debugRun: true
    expected: 18f47a30
    knownErrors:
    source: abc
    
  - part: 2
    run: true
    debugRun: true
    expected: 05ace8e3
    knownErrors:
    source: abc 
    
live:
  - part: 1
    run: true
    debugRun: true
    expected: f77a0e6e
    knownErrors:
    source: live.txt

  - part: 2
    run: true
    debugRun: true
    expected: 999828ec
    knownErrors:
    source: live.txt
