
name: Printing Department
year: 2025
day: 4
benchmark: true

tests:
  - part: 1
    run: true
    debugRun: true
    expected: 13
    knownErrors:
    source: test.txt
    
  - part: 2
    run: true
    debugRun: true
    expected: 43
    showVisualisation: true
    knownErrors:
    source: test.txt
    
live:
  - part: 1
    run: true
    debugRun: true
    expected: 1457
    knownErrors:
    source: live.txt

  - part: 2
    run: true
    debugRun: true
    showVisualisation: true
    expected: 8310
    knownErrors:
    source: live.txt

