
name: Lobby
year: 2025
day: 3

tests:
  - part: 1
    run: true
    debugRun: true
    expected: 357
    knownErrors:
    source: test.txt
    
  - part: 2
    run: true
    debugRun: true
    expected: 3121910778619
    knownErrors:
    source: test.txt
    
live:
  - part: 1
    run: true
    debugRun: true
    expected: 17330
    knownErrors:
    source: live.txt

  - part: 2
    run: true
    debugRun: true
    expected: 171518260283767
    knownErrors:
    source: live.txt
